# Generated by Django 3.2.7 on 2021-10-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20211014_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meeting_image'),
        ),
    ]
