# Generated by Django 3.2.7 on 2021-10-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meeting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, default='{"text" : "", "recommend_user": [{"text": ""}],"recommend_topic": [{"text": ""}]}', null=True),
        ),
    ]
