# Generated by Django 3.2.7 on 2021-10-19 18:14

from django.db import migrations, models
import meeting.models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_meeting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=meeting.models.path_and_rename),
        ),
    ]
