# Generated by Django 3.2.7 on 2021-10-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20211020_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.CharField(choices=[('MON', '월'), ('TUE', '화'), ('WED', '수'), ('THUR', '목'), ('FRI', '금'), ('SAT', '토'), ('SUN', '일')], max_length=8, unique=True),
        ),
    ]
