# Generated by Django 3.2.7 on 2021-10-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_alter_days_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.CharField(choices=[('0_MON', '월'), ('1_TUE', '화'), ('2_WED', '수'), ('3_THUR', '목'), ('4_FRI', '금'), ('5_SAT', '토'), ('6_SUN', '일')], max_length=8, unique=True),
        ),
    ]
