# Generated by Django 3.2.7 on 2021-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_meetinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='meeting.Days'),
        ),
    ]
