# Generated by Django 3.2.7 on 2021-10-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_alter_meeting_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='days',
            field=models.ManyToManyField(blank=True, to='meeting.Days'),
        ),
    ]
