# Generated by Django 3.2.7 on 2021-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_alter_meeting_days'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meetinglog',
            constraint=models.UniqueConstraint(fields=('meeting', 'date'), name='only one meeting for each day'),
        ),
    ]
