# Generated by Django 3.2.7 on 2021-11-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_meetinglog_only one meeting for each day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeetingenter',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meetinglog'),
        ),
        migrations.AddConstraint(
            model_name='usermeetingenter',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='user has already entered'),
        ),
    ]
