# Generated by Django 3.2.7 on 2021-11-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_meeting_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeetingenter',
            name='agora_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='channel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
