# Generated by Django 3.2.7 on 2021-11-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0017_remove_usermeetingenter_agora_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='sub_topics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
