# Generated by Django 3.2.7 on 2021-11-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_manner_point'),
        ('meeting', '0019_alter_meeting_sub_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
