# Generated by Django 3.2.7 on 2021-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0020_meeting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinglog',
            name='alarm_cnt_fake',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetinglog',
            name='alarm_fake_add_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetinglog',
            name='enter_cnt_fake',
            field=models.IntegerField(default=0),
        ),
    ]
