# Generated by Django 3.2.7 on 2021-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0021_auto_20211119_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
