# Generated by Django 3.2.7 on 2021-11-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0022_alter_meeting_is_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeetingenter',
            name='meeting_review_alarm_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
