# Generated by Django 3.2.7 on 2022-01-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0024_auto_20211216_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinglog',
            name='agora_user_list',
            field=models.TextField(default='[]'),
        ),
    ]
