# Generated by Django 3.2.7 on 2022-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0025_meetinglog_agora_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='meeting.Days'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetinglog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
