# Generated by Django 3.2.7 on 2022-01-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0026_auto_20220118_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
    ]
