# Generated by Django 3.2.7 on 2022-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0027_meeting_is_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinglog',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
