# Generated by Django 3.2.7 on 2022-02-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0028_meetinglog_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='days',
            field=models.ManyToManyField(blank=True, to='meeting.Days'),
        ),
    ]
