# Generated by Django 3.2.7 on 2022-02-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0029_alter_meeting_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinglog',
            name='share_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
