# Generated by Django 3.2.7 on 2021-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
