# Generated by Django 3.2.7 on 2021-10-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_temperature_user_manner_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
