# Generated by Django 3.2.7 on 2021-11-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_token"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["token"], name="user_user_token_dc846c_idx"),
        ),
    ]
