# Generated by Django 3.2.7 on 2021-11-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_user_user_token_dc846c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manner_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
