# Generated by Django 3.2.7 on 2021-11-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_manner_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
