# Generated by Django 3.2.7 on 2021-12-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_manner_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
