# Generated by Django 3.2.7 on 2021-10-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_meetinglog'),
        ('alarmtalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeetingalarm',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meetinglog'),
        ),
    ]
