# Generated by Django 3.2.7 on 2021-12-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmtalk', '0003_usermeetingalarm_only one alarm for each meeting - user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeetingalarm',
            name='hour_left_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
