# Generated by Django 3.2.7 on 2021-11-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingentercode',
            name='code',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingentercode',
            name='agora_token',
            field=models.TextField(),
        ),
    ]
