# Generated by Django 3.2.7 on 2021-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agora", "0002_auto_20211111_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingentercode",
            name="agora_token",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="meetingentercode",
            name="code",
            field=models.CharField(max_length=100),
        ),
    ]
