# Generated by Django 3.2.7 on 2021-11-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agora", "0003_auto_20211115_1150"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="meetingentercode",
            index=models.Index(
                fields=["code", "is_valid"], name="agora_meeti_code_8dcc3b_idx"
            ),
        ),
    ]
