# Generated by Django 3.2.7 on 2021-12-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_url', models.CharField(max_length=200)),
                ('karrot_scheme_url', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='shareurl',
            index=models.Index(fields=['origin_url'], name='share_share_origin__81596a_idx'),
        ),
        migrations.AddIndex(
            model_name='shareurl',
            index=models.Index(fields=['code'], name='share_share_code_a3bb84_idx'),
        ),
    ]
