# Generated by Django 3.2.7 on 2021-12-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareurl',
            name='access_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
