# Generated by Django 3.2.7 on 2021-10-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_meetinglog_only one meeting for each day'),
        ('user', '0003_user_token'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.meetinglog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
