# Generated by Django 3.2.7 on 2021-12-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_meetingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='useropinion',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
