name: Deploy to dev

on:
  push:
    branches: [develop]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Check Python version # checking the python version to see if 3.x is installed.
      run: python --version
      
    - name: Install Dependencies
      run: |
        cd ap-madang
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env
      run: |
        cd ap-madang
        touch .env
        echo DEBUG="False" >> .env
        echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
        echo AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        cat .env
  
    - name: Collect Static
      run: |
        cd ap-madang
        python manage.py collectstatic --noinput
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to ap-madang-dev-sub
      run: |
        echo "--- Installing EB CLI ---"
        python -m pip install --upgrade pip
        pip install awsebcli --upgrade
        eb --version
        echo "--- Start EB deploy ---"
        cd ap-madang
        eb init --region ap-northeast-2 --platform "Python 3.8 running on 64bit Amazon Linux 2" ap-madang
        eb use ap-madang-dev-sub
        eb deploy
    
    - name: swap urls
      run: |
        cd ap-madang
        eb swap ap-madang-dev --destination_name ap-madang-dev-sub
        
    
    - name: Deploy to ap-madang-dev
      run: |
        echo "--- Installing EB CLI ---"
        python -m pip install --upgrade pip
        pip install awsebcli --upgrade
        eb --version
        echo "--- Start EB deploy ---"
        cd ap-madang
        eb init --region ap-northeast-2 --platform "Python 3.8 running on 64bit Amazon Linux 2" ap-madang
        eb use ap-madang-dev
        eb deploy

    - name: swap urls back
      run: |
        cd ap-madang
        eb swap ap-madang-dev --destination_name ap-madang-dev-sub
