name: Deploy to dev

on:
  push:
    branches: [ develop]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Check Python version # checking the python version to see if 3.x is installed.
      run: python --version
      
    - name: Install Dependencies
      run: |
        cd ap-madang
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip freeze > requirements.txt
    - name: create .env
      run: |
        cd ap-madang
        touch .env
        echo DEBUG="False" >> .env
        echo DB_PROD_NAME="${{ secrets.DB_PROD_NAME }}" >> .env
        echo DB_PROD_USER="${{ secrets.DB_PROD_USER }}" >> .env
        echo DB_PROD_PASSWORD="${{ secrets.DB_PROD_PASSWORD }}" >> .env
        echo DB_PROD_HOST="${{ secrets.DB_PROD_HOST }}" >> .env
        echo DB_PROD_PORT="${{ secrets.DB_PROD_PORT }}" >> .env
        echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
        cat .env
    # - name: Run Migrations
    #  run: |
    #    cd ap-madang
    #    python manage.py migrate
    - name: Collect Static
      run: |
        cd ap-madang
        python manage.py collectstatic
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_NAME }}
    
    - name: Deploy to EB-cli
      run: |
        echo “--- Installing EB CLI ---”
        python -m pip install --upgrade pip
        pip install awsebcli --upgrade
        eb --version
        echo “--- Start EB deploy ---”
        cd ap-madang
        eb init --region ap-northeast-2 --platform “Python 3.8 running on 64bit Amazon Linux 2" ap-madang
        eb use ap-madang-dev
        eb deploy
